required_checks:
  script:
    - /ws_scripts/ci/module-required-checks.sh
  tags:
    - plutogo_ws

optional_checks:
  script:
    - /ws_scripts/ci/module-optional-checks.sh
  tags:
    - plutogo_ws
  allow_failure: true


build_workspace:
  script:
    - /ws_scripts/ci/module-build-workspace.sh
  tags:
    - plutogo_ws
