scan_filter_chain:
- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 4
    max_angle: 176
    neighbors: 3
    window: 1

- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    max_x: 0.4
    max_y: 0.4
    max_z: 0.4
    min_x: -0.4
    min_y: -0.4
    min_z: -0.3
- name: footprint_filter
  type: laser_filters/LaserScanFootprintFilter
  params:
    target_frame: odom_combined
    inscribed_radius: 0.45
