min_sensor_dist: 0.02

self_see_default_padding: 0.01

self_see_links:
  - name: base_link
    padding: 0.01
    scale: 1.0
  - name: laser360
  - name: left_front_wheel_link
  - name: left_middle_wheel_link
  - name: left_rear_wheel_link
  - name: right_front_wheel_link
  - name: right_middle_wheel_link
  - name: right_rear_wheel_link
  - name: rotunit_box_link
  - name: rotunit_mount_link
  - name: rotunit_support_link
  - name: rotunit_turntable_link
