TrajectoryPlannerROS:
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 2.4
  max_vel_x: 0.45
  min_vel_x: 0.02
  max_vel_theta: 0.9
  min_vel_theta: 0.03
  min_in_place_vel_theta: 0.1
  escape_vel: -0.4
  holonomic_robot: false

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false

  sim_time: 2.0
  sim_granularity: 0.05
  angular_sim_granularity: 0.03
  vx_samples: 8
  vtheta_samples: 30
  controller_frequency: 20

  meter_scoring: true
  pdist_scale: 0.6
  gdist_scale: 0.6
  occdist_scale: 0.01
  heading_lookahead: 0.4
  heading_scoring: true
  heading_scoring_timestep: 0.8
  dwa: true
  publish_cost_grid_pc: false
  global_frame_id: map

  oscillation_reset_dist: 0.05
  prune_plan: true

  escape_vel: -0.1
